/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "test_circuits/example.v:1.1-3.10" *)
module example(a, b, c, y);
  (* src = "test_circuits/example.v:2.15-2.20" *)
  wire _0_;
  (* src = "test_circuits/example.v:1.22-1.23" *)
  input a;
  wire a;
  (* src = "test_circuits/example.v:1.31-1.32" *)
  input b;
  wire b;
  (* src = "test_circuits/example.v:1.40-1.41" *)
  input c;
  wire c;
  (* src = "test_circuits/example.v:1.50-1.51" *)
  output y;
  wire y;
  assign _0_ = a & (* src = "test_circuits/example.v:2.15-2.20" *) b;
  assign y = _0_ | (* src = "test_circuits/example.v:2.14-2.25" *) c;
endmodule
